### ISSUE TITLE
Does 5ACCA298 CRC-32 diddy kong even exist ?

### ISSUE THREAD

**Issue by BenoitAdam** [gallaux/NintendoRomHacks#1]
For now I got this : 

![image](https://github.com/gallaux/NintendoRomHacks/assets/45485644/f66bf358-7a37-4611-8159-af10a9c12b14)

Can't find 5ACCA298 even if it's label USA En Fr Rev 1

**Comment by gallaux** [comment]
Look for the No-Intro: Nintendo 64 (Big Indian) set. This is the correct CRC for Diddy Kong Racing (USA) (En,Fr) (Rev 1)

**Comment by BenoitAdam** [comment]
Ah yes nice, now it works, thanks
